# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-25 00:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20170925_0036'),
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='journals',
            old_name='account_id',
            new_name='account',
        ),
        migrations.AddField(
            model_name='journals',
            name='customer',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='accounts.Customers'),
            preserve_default=False,
        ),
    ]
