# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-25 00:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0003_remove_journals_amount_to_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journals',
            name='transaction_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
