# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-25 01:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0004_auto_20170925_0051'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='journals',
            name='account',
        ),
        migrations.RemoveField(
            model_name='journals',
            name='customer',
        ),
    ]
