# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-25 01:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20170925_0051'),
        ('transactions', '0005_auto_20170925_0111'),
    ]

    operations = [
        migrations.AddField(
            model_name='journals',
            name='account',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='accounts.Accounts'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='journals',
            name='customer',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='accounts.Customers'),
            preserve_default=False,
        ),
    ]
