# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-25 04:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0006_auto_20170925_0120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journals',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
