# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-25 17:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0008_auto_20170925_1632'),
    ]

    operations = [
        migrations.AddField(
            model_name='journals',
            name='payment_amount',
            field=models.FloatField(default=0),
        ),
    ]
