# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-24 07:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Accounts',
            fields=[
                ('account_id', models.IntegerField(primary_key=True, serialize=False)),
                ('login_name', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('customer_id', models.IntegerField(primary_key=True, serialize=False)),
                ('customer_name', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=200)),
                ('phone_number', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Journals',
            fields=[
                ('transaction_id', models.IntegerField(primary_key=True, serialize=False)),
                ('transaction_type', models.CharField(max_length=20)),
                ('timestamp', models.DateTimeField(verbose_name='date of transaction')),
                ('purchase_amount', models.FloatField(default=0)),
                ('amount_to_date', models.IntegerField(default=0)),
                ('account_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Accounts')),
            ],
        ),
        migrations.AddField(
            model_name='accounts',
            name='customer_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Customers'),
        ),
    ]
