# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-24 21:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='journals',
            name='account_id',
        ),
        migrations.DeleteModel(
            name='Journals',
        ),
    ]
