# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-25 00:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20170925_0036'),
    ]

    operations = [
        migrations.AddField(
            model_name='accounts',
            name='principal',
            field=models.FloatField(default=0),
        ),
    ]
